{
    "name": "MLR Ecommerce Now Payments",
    "summary": "MLR Ecommerce Now Payments",
    "author": "MLR - MI Lightning Rod",
    "website": "https://www.milightningrod.com",
    "category": "Ecommerce",
    "version": "16.0",
    "depends": ["website", "mlr_ecommerce_cryptopayments"],
    "data": [
        "views/now_payment_template.xml",
        "data/now_payment_provider_data.xml",
        "views/now_payment_form.xml",
        "data/now_payment_icons.xml",
        "views/now_payment_provider.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    "license": "LGPL-3",
}
