{
    "name": "Secure Crypto Transfers and Event Ledger",
    "version": "18.0.2.0.0",
    "summary": "Verified outbound crypto transfers with an immutable event ledger",
    "category": "Accounting",
    "author": "Miler",
    "license": "AGPL-3",
    "depends": [
        "base",
        "account",
        "payment",
        "point_of_sale",
        "account_cryptocurrency",
    ],
    "data": [
        "security/crypto_security.xml",
        "security/ir.model.access.csv",
        "data/cashout_sequence.xml",
        "views/cashout_provider_views.xml",
        "views/cashout_config_views.xml",
        "views/cashout_payout_views.xml",
        "views/crypto_ledger_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
